#!/bin/bash

# Config
# -----------------------------------------------------------------------------

# User downloads directory
DOWNLOADS_DIR="${HOME}/Downloads/"

# Bashie lib folder
BASHIE_LIB="${HOME}/.bashie/lib"

# Default editor
EDITOR="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
#EDITOR="atom"
