#!/bin/bash

# ==============================================================================
# Aliases
# ==============================================================================


# Default editor
alias e=$EDITOR

# ------------------------------------------------------------------------------
# Clear view
# ------------------------------------------------------------------------------
alias c="clear"

# ------------------------------------------------------------------------------
# Apache Hosts
# ------------------------------------------------------------------------------
alias vhosts="e /private/etc/apache2/extra/httpd-vhosts.conf"

# ------------------------------------------------------------------------------
# System Hosts
# ------------------------------------------------------------------------------
alias hosts="e /etc/hosts"

# ------------------------------------------------------------------------------
# Quick Access Downloads
# ------------------------------------------------------------------------------
alias downloads="cd ~/Downloads/"

# ------------------------------------------------------------------------------
# View Recent Donwloads
# ------------------------------------------------------------------------------
alias downloads-view="sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'select LSQuarantineDataURLString from LSQuarantineEvent'"

# ------------------------------------------------------------------------------
# Delete Download History
# ------------------------------------------------------------------------------
alias downloads-deletehistory="sqlite3 ~/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV* 'delete from LSQuarantineEvent'"

# ------------------------------------------------------------------------------
# Up a folder tree
# ------------------------------------------------------------------------------
alias ..="cd .."

# Back a folder action
alias b="cd -"

# Show all files (inc. hidden) colorized in long format
alias l="ls -Gla"

# List all files colorized in long format
alias l-files="ls -Gl"

# Only dirs
alias l-dir='ls -l | grep "^d"'

# Symbolic Link
alias link='ln -s $1 $2'

# Compress
alias compress='tar -jcvf $1 $2'

# Uncompress
alias uncompress='tar -jxvf $1'

# Tell me the time
alias thetime=date

# Show/hide hidden files in Finder
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

# Delete easily
alias delete="rm -rf $1"

# Delete easily, please
alias delete-please="sudo rm -rf $1"

# Run Javascript
alias js="/System/Library/Frameworks/JavaScriptCore.framework/Versions/Current/Resources/jsc"

# Copy public DSA key to clipboard
alias sshkey="cat ~/.ssh/id_dsa.pub | pbcopy && echo 'Copied to clipboard.'"

# Local tunnel
alias tunnel="ngrok"
