#!/bin/bash

# Bashie Functions
# =============================================================================

# Update .bashie
function bashie_update () {

    notice_start
    echo 'Updating .bashie'
    notice_end

    cd ~/.bashie/
    git pull
    source ~/.bash_profile
    cd

}

# Reload .bashie
function bashie_reload () {

    notice_start
    echo 'Reloading .bashie'
    notice_end

    source ~/.bash_profile
    
}

# Edit .bashie
function bashie_edit () {

    notice_start
    echo 'Editing .bashie'
    notice_end

    e ~/.bashie
    
}