#!/bin/bash

# Bashie Functions
# =============================================================================

function bashie () {

    case $1 in
    "update")

        notice_start
        echo 'Updating .bashie'
        notice_end

        cd ~/.bashie/
        git pull
        source ~/.bash_profile
        cd

    ;;
    "reload")

        notice_start
        echo 'Reloading .bashie'
        notice_end

        source ~/.bash_profile

    ;;
    "edit")

        notice_start
        echo 'Editing .bashie'
        notice_end

        e ~/.bashie

    ;;
    "push")

        notice_start
        echo 'Pushing .bashie'
        notice_end

        cd ~/.bashie/
        git add .
        git commit -m "auto push"
        git push
        source ~/.bash_profile
        cd

    ;;
    esac

}