#!/bin/bash

# =============================================================================
# Folder shortcuts
# =============================================================================


# Development
alias code="cd ~/Dropbox/Code/"

# Volumes
alias vols="cd /Volumes/"

# Dropbox
alias box="cd ~/Dropbox/"

# ICE
alias docs="cd ~/Documents/"
