#!/bin/bash

# =============================================================================
# Folder shortcuts
# =============================================================================


# Sites
alias sites="cd ~/Sites/"

# Development
alias dev="cd ~/Development/"

# Clients
alias clients="cd ~/Clients/"

# Voluments
alias vols="cd /Volumes/"

# Voluments
alias box="cd ~/Dropbox/"