#!/bin/bash

# =============================================================================
# Folder shortcuts
# =============================================================================


# Development
alias dev="cd ~/Dropbox/Development/"

# Volumes
alias vols="cd /Volumes/"

# Dropbox
alias box="cd ~/Dropbox/"

# ICE
alias docs="cd ~/Documents/"
