#!/bin/bash

# Fuctions
# -----------------------------------------------------------------------------


# Restart Apache easily
function apache () {
    sudo apachectl $1
    echo -e "\033[0;35m"
    echo "$1 apache"
    notice_end
}

# Make the file and open it
function makeopen () {
    touch $1 | e $1
}

# Formats unix timestamp
function todate () {
    echo -e "\033[0;33m"
    perl -e "require 'ctime.pl'; print &ctime($1);"
    notice_end
}

function server () {
    php -S $@ | chrome http://$@
}

# Get IP
function ip () {
    noitce-start
    echo "Outside IP"
    dig +short myip.opendns.com @resolver1.opendns.com
    notice_end
}


# Connect notice for ssh
function notice_connect () {
    notice_start
    echo -e "Connecting to \033[1;32m$1\033[0;32m"
    notice_end
}


# Start of notice
function notice_start () {
    echo -e "\033[0;35m"
}

# End of notice
function notice_end () {
    echo "------------------------------------------------------------"
    echo -e "\033[0m"
}
