#!/bin/bash

# Fuctions
# -----------------------------------------------------------------------------


# Update .bashie
update-bashie () {
    cd ~/.bashie/
    git pull
    source ~/.bash_profile
    cd
}

# Restart Apache easily
apache () {
    sudo apachectl $1
    echo -e "\033[0;35m"
    echo "$1 apache"
    notice-end
}

# Make the file and open it
makeopen () {
    touch $1 | e $1
}

# Formats unix timestamp
todate () {
    echo -e "\033[0;33m"
    perl -e "require 'ctime.pl'; print &ctime($1);"
    notice-end
}



# Get IP
ip () {
    noitce-start
    echo "Outside IP"
    dig +short myip.opendns.com @resolver1.opendns.com
    notice-end
}


# Install Laravel and configure
install-laravel () {
    notice-start
    echo "Installing Laravel into '$1'"
    notice-end

    git clone https://github.com/laravel/laravel.git $1
    cd $1
    
    # Required for getting L4 dev
    git reset --hard HEAD
    git checkout develop

    # Do the house cleaning
    composer install
    artisan key:generate
    chmod -R 0777 app/storage/
    rm -rf .git
}


# Install Templatie
install-templatie () {
    notice-start
    echo "Installing Templatie into $1"
    notice-end
    git clone https://github.com/WolfieZero/templatie.git $1
    cd $1
    rm -rf .git
}


# Connect notice for ssh
notice-connect () {
    notice-start
    echo -e "Connecting to \033[1;32m$1\033[0;32m"
    notice-end
}


# Start of notice
notice-start () {
    echo -e "\033[0;35m"
}

# End of notice
notice-end () {
    echo "------------------------------------------------------------"
    echo -e "\033[0m" 
}
