#!/bin/bash

# Fuctions
# -----------------------------------------------------------------------------


# Restart Apache easily
function apache () {
    sudo apachectl $1
    echo -e "\033[0;35m"
    echo "$1 apache"
    notice_end
}

# Make the file and open it
function makeopen () {
    touch $1 | e $1
}

# Formats unix timestamp
function todate () {
    echo -e "\033[0;33m"
    perl -e "require 'ctime.pl'; print &ctime($1);"
    notice_end
}

function server () {
    php -S $@ | chrome http://$@
}

# Get IP
function ip () {
    notice_start
    echo "Outside IP"
    dig +short myip.opendns.com @resolver1.opendns.com
    notice_end
}


# Connect notice for ssh
function notice_connect () {
    notice_start
    echo -e "Connecting to \033[1;32m$1\033[0;32m"
    notice_end
}


# Start of notice
function notice_start () {
    echo -e "\033[0;35m"
}

# End of notice
function notice_end () {
    echo "------------------------------------------------------------"
    echo -e "\033[0m"
}

# toggle iTerm Dock icon
# add this to your .bash_profile or .zshrc
function toggleiTerm() {
	pb='/usr/libexec/PlistBuddy'
	iTerm='/Applications/iTerm.app/Contents/Info.plist'

	echo "Do you wish to hide iTerm in Dock?"
	select ync in "Hide" "Show" "Cancel"; do
	    case $ync in
	        'Hide' )
	        	$pb -c "Add :LSUIElement bool true" $iTerm
	        	echo "relaunch iTerm to take effectives"
	        	break
	        	;;
	        'Show' )
	        	$pb -c "Delete :LSUIElement" $iTerm
	        	echo "run killall 'iTerm' to exit, and then relaunch it"
	        	break
	        	;;
		'Cancel' )
			break
			;;
	    esac
	done
}
