#!/bin/bash

# =============================================================================
# ICE Stuff
# =============================================================================

# Vagrant ICE box
alias icebox="cd ~/icebox/"

# ICE Projects
alias iceprojects="cd ~/Project/"

# ICE Login
alias icelogins="e ~/Dropbox/ICE/Logins"
