#!/bin/bash

# Laravel 
# =============================================================================


# Install Laravel and configure
# -----------------------------------------------------------------------------

function install_laravel () {
    notice_start
    echo "Installing Laravel into '$1'"
    notice_end

    git clone https://github.com/laravel/laravel.git $1
    cd $1

    git checkout develop

    # Do the house cleaning
    composer install
    artisan key:generate
    chmod -R 0777 app/storage/
    rm -rf .git
}


# Artisan for Laravel (still need to cd into directory)
# -----------------------------------------------------------------------------

alias artisan='php artisan'