#!/bin/bash

# =============================================================================
# Laravel
# =============================================================================


# -----------------------------------------------------------------------------
# Install Laravel and configure
# -----------------------------------------------------------------------------

function laravel_install () {
    notice_start
    echo "Installing Laravel into '$1'"
    notice_end

    composer create-project laravel/laravel $1 --prefer-dist

    cd $1

    # Do the house cleaning
    #artisan key:generate
    chmod -R 0777 app/storage/
    rm -rf .git
}


# -----------------------------------------------------------------------------
# Artisan for Laravel (still need to cd into directory)
# -----------------------------------------------------------------------------

alias artisan='php artisan'