#!/bin/bash

# =============================================================================
# Sublime Text 3 Function
# =============================================================================


function sublime () {

    case $1 in
    "push")

        notice_start
        echo 'Pushing Sublime Text 3 to Repo'
        notice_end

        cd ~/Library/Application\ Support/Sublime\ Text\ 3
        git pull
        cd

    ;;
    "update")

        notice_start
        echo 'Updating Sublime Text 3 from Repo'
        notice_end

        cd ~/Library/Application\ Support/Sublime\ Text\ 3
        git add .
        git commit -m "auto push"
        git push
        cd

    ;;
    esac

}