#!/bin/bash

# WordPress
# =============================================================================


function wordpress() {

    case $1 in
    "install")
        _wp_install $1
    ;;
    "theme")
        _wp_make_theme $1
    ;;
    esac

}



# Make Theme
# -----------------------------------------------------------------------------

function _wp_make_theme () {

    notice_start
    echo "Making Theme"
    notice_end

    git clone git@github.com:Automattic/_s.git .


    echo 'task goes here' | cat - TODO.md > temp && mv temp TODO.md

}


# Install
# -----------------------------------------------------------------------------

function _wp_install () {

    notice_start
    echo "Installing WordPress"
    notice_end

    composer create-project wolfiezero/wp-kickstart ./
    delete vendor

}